apiVersion: v1
kind: Pod
spec:
  containers:
    - name: centospy
      image: orelbriga/centos-py:fail
      imagePullPolicy: "IfNotPresent"
      resources:
        limits:
          memory: "2048Mi"
        requests:
          memory: "1024Mi"
      tty: true