apiVersion: v1
kind: Pod
spec:
  containers:
    - name: gradle
      image: gradle:jdk11
      imagePullPolicy: "IfNotPresent"
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: "2048Mi"
        requests:
          memory: "1024Mi"
      volumeMounts:
        - mountPath: /home/gradle/.gradle/caches/modules-2
          name: gradle-cache
    - name: docker
      image: docker
      imagePullPolicy: "IfNotPresent"
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: "1024Mi"
        requests:
          memory: "512Mi"
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: gradle-cache
      hostPath:
        path: /root/.gradle-ro-cache/modules-2