# Deployment Config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      securityContext:
        fsGroup: 0
        runAsUser: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - jenkins-node
      tolerations:
        - key: node-type
          operator: Equal
          value: jenkins
          effect: NoSchedule
      containers:
        - name: jenkins
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          ports:
            - name: httpport
              containerPort: {{ .Values.service.httpPort }}
            - name: jnlpport
              containerPort: {{ .Values.service.jnlpPort }}
          volumeMounts:
            - name: jenkins-data
              mountPath: {{ .Values.volumeMountPath }}
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaimName }}
