# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistentVolume.capacity.storage }}
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.persistentVolumeClaim.name }}


---
#PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}




